/**
 * ---
 * Minimal structural representation of a PostgreSQL error
 * as emitted by common Node.js drivers (e.g. pg).
 * ---
 * All properties except `code` and `message` are optional because
 * PostgreSQL includes them only when relevant for a specific error.
 * ---
 * `code` is the SQLSTATE error code (5-character string).
 * See: [https://www.postgresql.org/docs/current/errcodes-appendix.html]
 */
interface PostgresError {
  /**
   * ---
   * SQLSTATE error code (e.g. '23505', '23503', '40001').
   */
  code: string;

  /**
   * ---
   * Human-readable error message generated by PostgreSQL.
   */
  message: string;

  /**
   * ---
   * Name of violated constraint (for constraint-related errors).
   */
  constraint?: string;

  /**
   * ---
   * Additional structured details (often includes conflicting key values).
   */
  detail?: string;

  /**
   * ---
   * Schema name where the error originated.
   */
  schema?: string;

  /**
   * ---
   * Column name involved in the error (e.g. NOT NULL violation).
   */
  column?: string;

  /**
   * ---
   * Table name involved in the error.
   */
  table?: string;

  /**
   * ---
   * Optional hint provided by PostgreSQL.
   */
  hint?: string;
}

/**
 * ---
 * SQLSTATE error code (5-character string).
 * See: [https://www.postgresql.org/docs/current/errcodes-appendix.html]
 */
type KnownSQLSTATE =
  | '23505' // unique_violation
  | '23503' // foreign_key_violation
  | '23502' // not_null_violation
  | '23514' // check_violation
  | '23P01' // exclusion_violation
  | '40001' // serialization_failure
  | '40P01' // deadlock_detected
  | '55P03' // lock_not_available
  | '08006' // connection_failure
  | '08003' // connection_does_not_exist
  | '22001' // string_data_right_truncation
  | '22007' // invalid_datetime_format
  | '25P02'; //in_failed_sql_transaction

function isKnownSQLSTATE(
  error: PostgresError,
  // eslint-disable-next-line prettier/prettier
): error is { code: KnownSQLSTATE; } & PostgresError {
  return [
    '23505',
    '23503',
    '23502',
    '23514',
    '23P01',
    '40001',
    '40P01',
    '55P03',
    '08006',
    '08003',
    '22001',
    '22007',
    '25P02',
  ].includes(error.code);
}

/**
 * ---
 * Runtime type guard that narrows an unknown thrown value
 * to a structural PostgreSQL error.
 * ---
 * This guard does not guarantee semantic correctness of fields,
 * only that the shape minimally matches a driver-emitted error.
 * ---
 * @param error - The error thrown by the PostgreSQL driver.
 */
function isPostgresError(error: unknown): error is PostgresError {
  return typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string';
}

/**
 * ---
 * Runtime type guard that narrows an unknown thrown value
 * to a structural PostgreSQL error with a known SQLSTATEs.
 * ---
 * This guard does not guarantee semantic correctness of fields,
 * only that the shape minimally matches a driver-emitted error.
 * ---
 * @param error - The error thrown by the PostgreSQL driver.
 */
export function isKnownPostgresError(error: unknown) {
  return isPostgresError(error) && isKnownSQLSTATE(error);
}
