// This file is autogenerated, see: ./config/next.config.ts
//@ts-nocheck

// config/next.config.ts
import path2 from "node:path";
import url2 from "node:url";

// src/lib/environment.ts
import path from "node:path";
import dotenv from "dotenv";
import url from "node:url";
import env from "env-var";
function resolve(metaUrl, relativePath) {
  return path.resolve(path.dirname(url.fileURLToPath(metaUrl)), relativePath);
}
var NODE_ENV = env.get("NODE_ENV").default("production").asEnum(["production", "development", "test"]);
dotenv.config({
  path: [
    // The path is one level higher since it will be used by next.js at the root level of the package.
    resolve(import.meta.url, `../../.env.${NODE_ENV}`),
    // Project relative path for typescript environment.
    resolve(import.meta.url, `../../../.env.${NODE_ENV}`),
    resolve(import.meta.url, `../../../../.env.${NODE_ENV}`)
  ]
});
function getEnvironment() {
  return {
    node: env.get("NODE_ENV").default("production").asEnum(["production", "development", "test"]),
    client: {
      url: env.get("CLIENT_URL").required().asUrlObject()
    },
    server: {
      url: env.get("SERVER_URL").required().asUrlObject()
    }
  };
}

// config/next.config.ts
function resolve2(metaUrl, relativePath) {
  return path2.resolve(path2.dirname(url2.fileURLToPath(metaUrl)), relativePath);
}
var environment = getEnvironment();
var next_config_default = {
  webpack(config) {
    config.resolve.alias.library = resolve2(import.meta.url, "../library/src");
    return config;
  },
  eslint: {
    // Enabled in root scripts.
    ignoreDuringBuilds: true
  },
  env: {
    NEXT_PUBLIC_ORIGIN: environment.client.url.origin
  },
  // Prevents errors in pnp, caused by attempts to work with virtual file system.
  serverExternalPackages: ["@electric-sql/pglite"],
  experimental: {
    typedRoutes: true
  },
  poweredByHeader: false
};
export {
  next_config_default as default
};
