// This file is autogenerated, see: ./config/next.config.ts
//@ts-nocheck

// ../library/src/resolve-path.ts
import path from "node:path";
import url from "node:url";
function resolvePath(metaUrl, relativePath) {
  return path.resolve(path.dirname(url.fileURLToPath(metaUrl)), relativePath);
}

// src/library/environment.ts
import dotenv from "dotenv";
import env from "env-var";
var NODE_ENV = env.get("NODE_ENV").default("production").asEnum(["production", "development", "test"]);
dotenv.config({
  path: [
    // The path is one level higher since it will be used by next.js at the root level of the package.
    resolvePath(import.meta.url, `../../.env.${NODE_ENV}`),
    // Project relative path for typescript environment.
    resolvePath(import.meta.url, `../../../.env.${NODE_ENV}`),
    resolvePath(import.meta.url, `../../../../.env.${NODE_ENV}`)
  ]
});
function getEnvironment() {
  return {
    node: env.get("NODE_ENV").default("production").asEnum(["production", "development", "test"]),
    client: {
      url: env.get("CLIENT_URL").required().asUrlObject()
    },
    server: {
      url: env.get("SERVER_URL").required().asUrlObject()
    }
  };
}

// config/next.config.ts
var environment = getEnvironment();
var next_config_default = {
  eslint: {
    // Enabled in root scripts.
    ignoreDuringBuilds: true
  },
  env: {
    NEXT_PUBLIC_ORIGIN: environment.client.url.origin
  },
  // Prevents errors in pnp, caused by attempts to work with virtual file system.
  serverExternalPackages: ["@electric-sql/pglite"],
  experimental: {
    typedRoutes: true
  },
  poweredByHeader: false
};
export {
  next_config_default as default
};
